parameters:
#    sss_to_do.example.class: SSS\ToDoBundle\Example

services:
#    sss_to_do.example:
#        class: %sss_to_do.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
