<?php

namespace SSS\UserBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * QuestionsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NotificationRepository extends EntityRepository
{
    public function findAllCategories($id){

    }
    public function getNotifs($user){
        $qb = $this->createQueryBuilder('n')
            ->where('n.new = true')
            ->andWhere('n.user = :user')
            ->setParameter(':user', $user)
            ->orderBy('n.date','DESC')
            ->getQuery();
        return $qb->getResult();
    }
}
