security:
    encoders:
        SSS\UserBundle\Entity\User: sha512

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER, ROLE_CLIENT, ROLE_AUDITEUR
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        main:
            id: fos_user.user_provider.username

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            pattern: ^/
            anonymous: true
            form_login:
                provider: main
                login_path: fos_user_security_login
                check_path: fos_user_security_check
            logout:
                path: fos_user_security_logout
            remember_me:
                key: %secret%

    access_control:
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY}
        - { path: ^/$, roles: IS_AUTHENTICATED_ANONYMOUSLY}
        - { path: ^/audit/$, roles: IS_AUTHENTICATED_ANONYMOUSLY}
        - { path: ^/audit/, roles: ROLE_AUDITEUR}
