<?php

namespace SSS\AuditBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * QuestionsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class QuestionsRepository extends EntityRepository
{
    public function findAllCategories($id){
        $qb = $this->_em->createQuery('SELECT DISTINCT q.categorie FROM SSSAuditBundle:Questions q WHERE q.typeAudit='.$id);
        return $qb->getResult();
    }
    public function findQuestionsByCategorieAndTypeAudit($cat, $audit){
        $qb = $this->createQueryBuilder('q')
            ->where('q.categorie = :categorie')
            ->andWhere('q.typeAudit = :type_audit')
            ->setParameter('categorie', $cat)
            ->setParameter('type_audit',$audit)
            ->getQuery();
        return $qb->getResult();
    }
    public function findNonQuestion($idNon){
        $length = count($idNon);
        $qb = $this->createQueryBuilder('q')
            ->where('q.id = :id')
            ->setParameter('id', $idNon[0]);
        for($i = 1; $i < $length; $i++){
            $qb->orWhere('q.id = :id'.$i)
                ->setParameter('id'.$i, $idNon[$i]);
        }
        return $qb->getQuery()->getResult();
         //var_dump($qb->getQuery());

    }
}
