parameters:
    sss_audit.consumer.access.class: SSS\AuditBundle\Work\AMQP\AMQPConsAccess

services:
    sss_audit.consumer.access:
        class: %sss_audit.consumer.access.class%
        arguments: [@security.context]
